### ISSUE TITLE
"Latest Posts" block typography does not react to font size change

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#6] opened 2023-04-04 15:13 UTC
@preda-bogdan I was working on a sidebar layout and added a "Latest Posts" block. It looks like it does not respond to the Text Size UI control. Maybe it has specific sizes defined somewhere in the core's css? 🤔 

It's in this page: https://fse-neve.vertisite.cloud/page-sidebar-layout/

![Screenshot 2023-04-04 at 6 07 30 PM](https://user-images.githubusercontent.com/4193672/229836575-0df22101-2b60-434c-924b-322f902fa92d.png)

I might collect a couple of few examples in other blocks like this. Will keep you posted.

**Comment by preda-bogdan** [comment] 2023-05-02 15:59
@JohnPixle Thank you for reminding me about this, I've submitted the changes to the design branch. The default size is now set inside `theme.json` as:
```json
"typography": {
    "fontSize": "var(--wp--preset--font-size--medium)",
    "fontWeight": "600"
}
```

Previously they were set inside the CSS styles which would not allow the set settings to override those.
Now they are provided as defaults for the `core/latest-posts` block which will allow them to be displayed as specified by the design but also be changed by the user.

Let me know if the issue is resolved for you now.

**Comment by preda-bogdan** [comment] 2023-05-04 12:48
@Codeinwp/qa-team Here, can you help to confirm that if you add the latest post block using the build from here: https://github.com/Codeinwp/neve-fse/pull/8 
1. You can change the font size and the change is also reflected inside the editor and on the front-end
2. The default font size when the bloc is added is the medium size, for the default setting.

Thank you!

**Comment by preda-bogdan** [comment] 2023-05-04 14:40
Ok thank you, I will then close it. No need to take more of the QA team's time.

**Closed as completed by preda-bogdan** 2023-05-04 14:40 UTC
Labels: small
